### ISSUE TITLE
DPT error

### ISSUE THREAD

**Issue by lgarcialara** [lucianoambrosini/Ambrosinus-Toolkit#2]
DPT is sending an error message:

1. Traceback (most recent call last):
  File "C:\GH_CPython\PythonFileWritten_2.py", line 58, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Thanks!

**Comment by lucianoambrosini** [comment]
Hello! Thanks for you feedback.
Seems that your machine is missing the "opencv-python" library... Simply try installing it through the CMD.exe on Windows OS and restart Rhino. Please, let me know

**Comment by lgarcialara** [comment]
> Hello! Thanks for you feedback. Seems that your machine is missing the "opencv-python" library... Simply try installing it through the CMD.exe on Windows OS and restart Rhino. Please, let me know

Thanks Luciano! issue was solve
Regards
Luis

**Comment by lucianoambrosini** [comment]
Hurray! 😊 Thanks for your feedback!
