### ISSUE TITLE
Stable Diffusion but on a "remote coputer"

### ISSUE THREAD

**Issue by pfmephisto** [lucianoambrosini/Ambrosinus-Toolkit#3]
Hi @lucianoambrosini,
Nice plugin :)
Is it possible to specify the ip and port for the Automatic1111 web api in the AleNG Component?
I have the scenario where I am running Grasshopper on my laptop but I have Stable Diffusion set up on a second PC on the same local network. It would be great if IP and Port could be customized, insted of having them hardcoded.

**Comment by lucianoambrosini** [comment]
Hello and thanks for your message. I will open IP and port asap 👍🏼😉

**Comment by pfmephisto** [comment]
Thanks a lot 😃

**Comment by lucianoambrosini** [comment]
Hey, please have a look at the [Ambrosinus-Toolkit v1.2.2 ](https://bit.ly/SDandCNinsideGH-Upd3) 😉

**Comment by pfmephisto** [comment]
Nice, thanks 😄
