### ISSUE TITLE
Ambrosinus-Toolkit available in Package Manager for Rhino 7 on Mac

### ISSUE THREAD

**Issue by jamesjoyce92** [lucianoambrosini/Ambrosinus-Toolkit#5]
Hey, 

first of all congrats for your amazing work! I like it a lot! I'm currently working on my Mac, and was happy as I could download your work in the package manager in Rhino 7. However when I try to use LaunchSD_loc Node, I get the error : 

`1. Solution exception:The method or operation is not implemented.`

My assumption is, that the package isn't supported on mac, right? 

On the other hand, the `view_caputure` node is working. (I was looking for years, after this kind of solution. Very handy!) 

Best 
Sven

**Comment by lucianoambrosini** [comment]
Hey, thank you for your feedback! 🙂
Unfortunately, most components (especially those for AI) have been developed for Windows OS. However, some features, like the one you mentioned, are purely based on Rhino/Grasshopper libraries so they might work properly.
..and I am happy to hear that view_capture is really worth it...I tried to do a bit more compared to the others on the markets 😉. Stay tuned! Thanks!

**Comment by lucianoambrosini** [comment]
Hey, thank you for your feedback! 🙂
Unfortunately, most components (especially those for AI) have been developed for Windows OS. However, some features, like the one you mentioned, are purely based on Rhino/Grasshopper libraries so they should work properly.
..and I am happy to hear that view_capture is really worth it...I tried to do a bit more compared to the others on the markets 😉. Stay tuned! Thanks!
